### ISSUE TITLE
github action fails

### ISSUE THREAD

**Issue by gutenfries** [gutenfries/gutenfries.deno.dev#6]
Github action fails with message
```
Relative import path "$fresh/plugins/twind.ts" not prefixed with / or ./ or ../
```

**Comment by gutenfries** [comment]
@shevernitskiy, please excuse the cold mention. In my frantic searching on the internet trying to fix this, I stumbled across a [blog post](https://pullanswer.com/questions/error-with-relative-import-path-on-deployment-to-deno-deploy) that you wrote about this exact issue. In the post, you refer to using the `--import-map` flag, and I tried that without luck. I was hoping maybe you had insight on the issue. thank you!

**Comment by shevernitskiy** [comment]
Hey!
I had that issue during deploing to deno deploy with `deployctl`. So, in my case that was `deployctl` bug, cause it don't get import pathes from file specified in `deno.json`. But you can use flag to force `deploctl` use your import map.
```sh
deployctl deploy --project=victory --import-map=import_map.json  ./main.ts 
```
I think you could fix your action like this
```yml
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "gutenfries"
          entrypoint: "./main.ts"
          import-map: "./import_map.json"
```
